In [2]:
from sklearn.datasets import load_iris

In [3]:
dataset = load_iris()

In [5]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [8]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [6]:
import pandas as pd
import numpy as np

In [9]:
df = pd.DataFrame(dataset.data, columns = dataset.feature_names)

In [10]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

Independent and Dependent Features

In [14]:
df['target'] = dataset.target

In [16]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [17]:
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Binary Classification

In [23]:
df_copy = df[df['target'] != 2]

In [20]:
df_copy.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [21]:
df_copy.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target  
95       1  
96       1  
97       1  
98       1  
99       1

In [30]:
X = df_copy.iloc[:,:-1]
y = df_copy.iloc[:,-1]

In [31]:
from sklearn.linear_model import LogisticRegression

In [32]:
## train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

In [33]:
classifier = LogisticRegression()

In [34]:
classifier.fit(X_train, y_train)

LogisticRegression()

In [44]:
classifier.predict_proba(X_test)

array([[0.00144451, 0.99855549],
       [0.01745661, 0.98254339],
       [0.00359664, 0.99640336],
       [0.96427472, 0.03572528],
       [0.93476204, 0.06523796],
       [0.96670676, 0.03329324],
       [0.99197567, 0.00802433],
       [0.03414716, 0.96585284],
       [0.97022597, 0.02977403],
       [0.97501069, 0.02498931],
       [0.94876941, 0.05123059],
       [0.95432911, 0.04567089],
       [0.00502877, 0.99497123],
       [0.98309763, 0.01690237],
       [0.01045624, 0.98954376],
       [0.97788605, 0.02211395],
       [0.00251305, 0.99748695],
       [0.00154296, 0.99845704],
       [0.96995374, 0.03004626],
       [0.95518866, 0.04481134],
       [0.00835685, 0.99164315],
       [0.02378303, 0.97621697],
       [0.95343728, 0.04656272],
       [0.98084327, 0.01915673],
       [0.02881772, 0.97118228],
       [0.97696692, 0.02303308],
       [0.97878312, 0.02121688],
       [0.01706457, 0.98293543],
       [0.96440543, 0.03559457],
       [0.0018048 , 0.9981952 ],
       [0.

In [35]:
## Prediction
y_pred = classifier.predict(X_test)

In [37]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1])

In [39]:
y_test

83    1
53    1
70    1
45    0
44    0
39    0
22    0
80    1
10    0
0     0
18    0
30    0
73    1
33    0
90    1
4     0
76    1
77    1
12    0
31    0
55    1
88    1
26    0
42    0
69    1
15    0
40    0
96    1
9     0
72    1
11    0
47    0
85    1
Name: target, dtype: int64

Confusion metrics, accuracy score, classification report

In [42]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [43]:
print(confusion_matrix(y_pred, y_test))
print(accuracy_score(y_pred, y_test))
print(classification_report(y_pred, y_test))

[[19  0]
 [ 0 14]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        14

    accuracy                           1.00        33
   macro avg       1.00      1.00      1.00        33
weighted avg       1.00      1.00      1.00        33



Hyperparameter Tuning

In [49]:
## GridSearchCV
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [50]:
parameters = {'penalty':('l1','l2','elasticnet',None),
              'C' : [1,10,20]
              }

In [51]:
clf = GridSearchCV(classifier, param_grid = parameters, cv = 5)

In [52]:
## Splitting of train data to validation data
clf.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20],
                         'penalty': ('l1', 'l2', 'elasticnet', None)})

In [53]:
clf.best_params_

{'C': 1, 'penalty': 'l2'}

In [54]:
classifier = LogisticRegression(C = 1, penalty = 'l2')

In [56]:
classifier.fit(X_train, y_train)

LogisticRegression(C=1)

In [57]:
## Prediction
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_pred, y_test))
print(accuracy_score(y_pred, y_test))
print(classification_report(y_pred, y_test))

[[19  0]
 [ 0 14]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        14

    accuracy                           1.00        33
   macro avg       1.00      1.00      1.00        33
weighted avg       1.00      1.00      1.00        33



In [58]:
## Randomized Search CV
from sklearn.model_selection import RandomizedSearchCV

In [60]:
random_clf = RandomizedSearchCV(LogisticRegression(), param_distributions=parameters, cv = 5)

In [61]:
random_clf.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 10, 20],
                                        'penalty': ('l1', 'l2', 'elasticnet',
                                                    None)})

In [62]:
random_clf.best_params_

{'penalty': 'l2', 'C': 10}